services:
  python:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: mywellness-class-booker-python
    working_dir: /src
    environment:
      - AWS_PROFILE=${AWS_PROFILE}
      - HWF_USERNAME=${HWF_USERNAME}
      - HWF_PASSWORD=${HWF_PASSWORD}
    volumes:
      - ./src/:/src/
#    command: tail -f /dev/null  # Keeps the container running for manual commands
  cdk:
    image: node:22.14.0-alpine3.21
    container_name: mywellness-class-booker-cdk
    working_dir: /aws
    environment:
      - AWS_PROFILE=${AWS_PROFILE}
      - APPLICATION_ENVIRONMENT=test
      - AWS_TAGS_ENVIRONMENT=dev
    volumes:
      - ./src/:/src/
      - ./aws/:/aws/
      - ~/.aws/:/root/.aws:ro
