# Use an official Python image as the base
FROM python:3.9-slim

# Set the working directory to /app
WORKDIR /src

## Copy the application code
COPY ../src .

# Install dependencies
RUN pip install -r requirements.txt
